// GENERATED BY FLUTTERFIRE CLI - Replace with your actual config after running:
// flutterfire configure --project=your-firebase-project-id
//
// Or manually fill in your Firebase project details below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// HOW TO GET YOUR CONFIG:
/// 1. Go to https://console.firebase.google.com/
/// 2. Create a new project (e.g., "dalali-app")
/// 3. Add an Android app with package name: com.dalali.app
/// 4. Download google-services.json and place it in android/app/
/// 5. Run: 
///    OR manually paste your values below.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '723762100065',
    projectId: 'dalali-83f65',
    authDomain: 'dalali-83f65.firebaseapp.com',
    storageBucket: 'dalali-83f65.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  // Android config from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojaQ6wfIhaAp5IsRZ98gVhE5GE8587tk',
    appId: '1:723762100065:android:5a605479aef44c03dc7720',
    messagingSenderId: '723762100065',
    projectId: 'dalali-83f65',
    storageBucket: 'dalali-83f65.firebasestorage.app',
  );

  // iOS config from GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0dHpLNP05EhhmzolrNh3Fd1f_iabIBWU',
    appId: '1:723762100065:ios:9629b28f482d5cbddc7720',
    messagingSenderId: '723762100065',
    projectId: 'dalali-83f65',
    storageBucket: 'dalali-83f65.firebasestorage.app',
    iosBundleId: 'dalali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '723762100065',
    projectId: 'dalali-83f65',
    storageBucket: 'dalali-83f65.firebasestorage.app',
    iosBundleId: 'dalali',
  );
}
